### ISSUE TITLE
NC: Update PTB and publish releases to pypi

### ISSUE THREAD

**Issue by ckunki** [exasol/notebook-connector#8]
See
* https://github.com/exasol/bucketfs-python/blob/main/.github/workflows/ci-cd.yml
* https://pypi.org/project/exasol-toolbox/

```[tasklist]
### Tasks
- [x] Update exasol python toolbox version to 0.5.0
- [ ] Fix build errors
- [ ] Publish releases to pypi
```
